### ISSUE TITLE
最新のEMSDKでビルドができない

### ISSUE THREAD

**Issue by nokotan** [nokotan/DxLibForHTML5-VSCode#2]
最新のEMSDKを使うと次のエラーが出てビルドができません。
```bat
Traceback (most recent call last):
  File "\*\*\*/emsdk/upstream/emscripten/emcc.py", line 3905, in <module>
    sys.exit(run(sys.argv))
  File "\*\*\*/emsdk/upstream/emscripten/emcc.py", line 2373, in run
    final = do_emscripten(final, shared.replace_or_append_suffix(target, '.mem'))
  File "\*\*\*/emsdk/upstream/emscripten/emcc.py", line 475, in do_emscripten
    emscripten.run(infile, outfile, memfile)
  File "\*\*\*/emsdk/upstream/emscripten/emscripten.py", line 2794, in run
    return temp_files.run_and_clean(lambda: emscripter(
  File "\*\*\*/emsdk/upstream/emscripten/tools/tempfiles.py", line 105, in run_and_clean
    return func()
  File "\*\*\*/emsdk/upstream/emscripten/emscripten.py", line 2795, in <lambda>
    infile, outfile_obj, memfile, temp_files, shared.DEBUG)
  File "\*\*\*/emsdk/upstream/emscripten/emscripten.py", line 2207, in emscript_wasm_backend
    glue, forwarded_data = compile_settings(temp_files)
  File "\*\*\*/emsdk/upstream/emscripten/emscripten.py", line 773, in compile_settings
    cwd=path_from_root('src'), env=env)
  File "\*\*\*/emsdk/upstream/emscripten/tools/jsrun.py", line 100, in run_js_tool
    return shared.check_call(command, *args, **kw).stdout
  File "\*\*\*/emsdk/upstream/emscripten/tools/shared.py", line 200, in check_call
    return run_process(cmd, *args, **kw)
  File "\*\*\*/emsdk/upstream/emscripten/tools/shared.py", line 181, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "D:/obj/windows-release/37amd64_Release/msi_python/zip_amd64/subprocess.py", line 474, in run
  File "D:/obj/windows-release/37amd64_Release/msi_python/zip_amd64/subprocess.py", line 926, in communicate
UnicodeDecodeError: 'cp932' codec can't decode byte 0x86 in position 24221: illegal multibyte sequence
ターミナルの処理が終了しました (終了コード: 1)
```

**Comment by nokotan** [comment]
最近のEMSDKのバックエンドとなるPythonが2.xから3.xに更新されて、エンコーディングの取り扱いが変わったのが原因だと判明しました。
手元のビルド環境で数か所変更を加えることでビルドが成功することを確認しています。
近々EMSDKにもissueを立てるのでしばらくお待ちください。

変更箇所は次の通りです。
shared.py (180)
```python
  if hasattr(subprocess, "run"):
    ret = subprocess.run(cmd, check=check, input=input, encoding="utf-8", *args, **kw)
    logger.debug(debug_text)
    return ret
```
shared.py (3430)
```python
  out = open(stdout, 'r', encoding="utf-8").read()
```

**Comment by nokotan** [comment]
[emscripten Issues](https://github.com/emscripten-core/emscripten/issues/10551) に報告済み、こちら側の Issue は閉じます。
